### PR TITLE
Fix CFBundleVersion for Carthage Installs

### LINKED ISSUE #99: CFBundleVersion is empty
The `CFBundleVersion` parameter in `Info.plist` is empty, which the App Store complains about. I was able to workaround the issue by setting a value via plistbuddy but it seems like `$(CURRENT_PROJECT_VERSION)` is not defined.

### PR DESCRIPTION
**Pull request by jbuckner**
Uploading to the App Store was failing when Seam3 was installed via Carthage. This is because `CURRENT_PROJECT_VERSION` was not set in the `project.pbxproj` file so when it compiled the `Info.plist` file, the `CFBundleVersion` was empty and the App Store was rejecting the upload. I was poking around and it looks like CocoaPods sets its own `CURRENT_PROJECT_VERSION` to 1 so that might be why it was fine with CocoaPods.

I saw 2 options for a fix here:
1. Update the `CURRENT_PROJECT_VERSION` in each of the targets' Build Settings and the respective Info.plist files would pick that up. This is kind of a pain since you have to go into each of the Target Build Settings and update each of the settings.
2. Update the Info.plist files directly. This felt more straight-forward since the Info.plist files are right at the top level of the project and easy to find.

If there's a better way than either of those, I'm open to changing it. They both seemed like a lot of work. Maybe just use a single `Info.plist` file for all 4 targets since they're all the same?

I set the `CFBundleVersion` in each of the `Info.plist` files to the current version and updated the other outdated versions.

I also organized the macOS and tvOS Info.plist files. The references were broken in the `pbxproj` file and the iOS/watchOS Info.plist files were organized in the `Assets/Resources` directory so now they're all together in `Assets/Resources`.

Fixes #99

### CODE REVIEW

**Comment by paulw11** [comment]
This is another Carthage problem that doesn't exist when you use it as a Pod.  The issue with the fix is that now there is an additional point of maintenance to have to update these version numbers when previously it was performed automatically if you used the Cocoapods problem.

I am in two minds here; Stuff like this is why I rejected the original PR that added Carthage support before accepting a later PR; it just seems too messy and manual.

**Comment by paulw11** [comment]
I don't know much about Carthage - Would [this](https://github.com/grpc/grpc-swift/pull/292/commits) be a better approach? It seems to have a ruby file that puts a version in when using Carthage.

**Comment by jbuckner** [comment]
Ah didn't see the previous PR. Yeah agreed. It's a lot of maintenance. What do you think of just setting the `CURRENT_PROJECT_VERSION` to 1 in the Target settings and just not worry about updating it? That's how it defaults for me anyways in new Xcode projects. It doesn't matter too much _what_ the `CFBundleVersion` is, so long as there is one.

**Comment by paulw11** [comment]
That is another approach.  It is just a shame to "break" something where Cocoapods does the right thing automatically.

**Comment by jbuckner** [comment]
@paulw11 I updated the PR with that approach and it pretty much leaves everything else the way it was (except fixing the links to Mac and tvOS Info.plist). Yeah CocoaPods works because it automatically sets that value in its `Pods.pbxproj` file to `1.0`. Carthage is much more hands off in that regard and will just use what you give it and the `CURRENT_PROJECT_VERSION` just wasn't set in the targets.

Does setting the `CURRENT_PROJECT_VERSION` in the project break CocoaPods?

**Pull request merged**
