### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by Kautenja**
* add a shared framework to the CocoaPods Example project for distributing through Carthage

### CODE REVIEW

**Comment by paulw11** [comment]
Carthage support adds too much junk to the Repo.

**Comment by Kautenja** [comment]
it hardly adds anything other than the configuration of the framework. less "junk" than all the cocoa pods boilerplate... but whatever

**Comment by paulw11** [comment]
Your pull request changed 71 files, most of which should be built rather than included in the repo as well as adding  things like .DS_Store

**Comment by Kautenja** [comment]
After reviewing the PR it looks like the majority of the files are from running the `pod install` command. Your .gitignore needs reviewed as it should really catch those alongside the general MacOS files like .DS_Store given that this is exclusively a MacOS project that is open source.

here's a macos git ignore
https://github.com/github/gitignore/blob/master/Global/macOS.gitignore

Only the project.pbxproj needs updated to support carthage with a cocoa touch framework that points to the source files in the Classes directory. I wont reopen a PR as i couldn't get the codebase to work anyway and ended up using  https://github.com/mentrena/SyncKit sorry for wasting your time with this issue.

**Pull request closed without merging**
